Rails:
  Enabled: true
AlignHash:
  # Alignment of entries using hash rocket as separator. Valid values are:
  #
  # key - left alignment of keys
  # 'a' => 2
  # 'bb' => 3
  # separator - alignment of hash rockets, keys are right aligned
  # 'a' => 2
  # 'bb' => 3
  # table - left alignment of keys, hash rockets, and values
  # 'a' => 2
  # 'bb' => 3
  EnforcedHashRocketStyle: table
  # Alignment of entries using colon as separator. Valid values are:
  #
  # key - left alignment of keys
  # a: 0
  # bb: 1
  # separator - alignment of colons, keys are right aligned
  # a: 0
  # bb: 1
  # table - left alignment of keys and values
  # a: 0
  # bb: 1
  EnforcedColonStyle: table
IfUnlessModifier:
  MaxLineLength: 100
LineLength:
  Max: 100
StringLiterals:
  EnforcedStyle: double_quotes
WhileUntilModifier:
  MaxLineLength: 100
MethodCalledOnDoEndBlock:
  Description: 'Avoid chaining a method call on a do...end block.'
  Enabled: true
ClassLength:
  Max: 400
Documentation:
  Enabled: false
